"""
Whilber-AI — Strategy Templates
====================================
Pre-built trading strategies users can load and customize.
"""

TEMPLATES = [
    {
        "id": "golden_cross",
        "name": "Golden Cross",
        "name_fa": "کراس طلایی",
        "icon": "✨",
        "category": "trend",
        "difficulty": "beginner",
        "description": "EMA 50 crosses above EMA 200 = Buy, crosses below = Sell",
        "description_fa": "کراس EMA 50 بالای EMA 200 خرید، پایین فروش",
        "strategy": {
            "name": "Golden Cross",
            "symbol": "XAUUSD",
            "timeframe": "H4",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "EMA",
                    "indicator_params": {"period": 50, "source": "close"},
                    "output": "value",
                    "condition": "crosses_above",
                    "compare_to": "indicator",
                    "compare_indicator": "EMA",
                    "compare_indicator_params": {"period": 200, "source": "close"},
                    "compare_output": "value",
                    "compare_value": 0,
                },
            ],
            "exit_take_profit": [{"type": "atr_tp", "params": {"multiplier": 3.0, "atr_period": 14}}],
            "exit_stop_loss": [{"type": "atr_sl", "params": {"multiplier": 2.0, "atr_period": 14}}],
            "exit_trailing": {"type": "trailing_atr", "value": 2.0, "atr_period": 14},
            "exit_break_even": {"trigger": 30, "lock": 5},
            "exit_time": None,
            "filters": [],
            "risk": {"preset": "moderate", "risk_per_trade": 2.0, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 3, "max_open_trades": 2, "max_drawdown": 20, "min_rr": 1.5},
        },
    },
    {
        "id": "rsi_bounce",
        "name": "RSI Bounce",
        "name_fa": "برگشت RSI",
        "icon": "📊",
        "category": "oscillator",
        "difficulty": "beginner",
        "description": "Buy when RSI crosses above 30, Sell when crosses below 70",
        "description_fa": "خرید وقتی RSI از ۳۰ بالا میره، فروش وقتی از ۷۰ پایین میاد",
        "strategy": {
            "name": "RSI Bounce",
            "symbol": "XAUUSD",
            "timeframe": "H1",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "RSI",
                    "indicator_params": {"period": 14},
                    "output": "value",
                    "condition": "crosses_above",
                    "compare_to": "fixed_value",
                    "compare_value": 30,
                    "compare_indicator": "",
                    "compare_indicator_params": {},
                    "compare_output": "value",
                },
            ],
            "exit_take_profit": [{"type": "atr_tp", "params": {"multiplier": 2.0, "atr_period": 14}}],
            "exit_stop_loss": [{"type": "atr_sl", "params": {"multiplier": 1.5, "atr_period": 14}}],
            "exit_trailing": None,
            "exit_break_even": {"trigger": 20, "lock": 3},
            "exit_time": {"bars": 20},
            "filters": [],
            "risk": {"preset": "conservative", "risk_per_trade": 1.5, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 5, "max_open_trades": 3, "max_drawdown": 15, "min_rr": 1.5},
        },
    },
    {
        "id": "bb_squeeze",
        "name": "Bollinger Squeeze",
        "name_fa": "فشرده بولینگر",
        "icon": "📉",
        "category": "volatility",
        "difficulty": "intermediate",
        "description": "Price breaks above upper BB with RSI > 50 confirmation",
        "description_fa": "شکست قیمت بالای باند بالایی بولینگر با تایید RSI بالای ۵۰",
        "strategy": {
            "name": "Bollinger Squeeze",
            "symbol": "XAUUSD",
            "timeframe": "H1",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "PRICE",
                    "indicator_params": {"source": "close"},
                    "output": "value",
                    "condition": "crosses_above",
                    "compare_to": "indicator",
                    "compare_indicator": "BB",
                    "compare_indicator_params": {"period": 20, "std_dev": 2.0},
                    "compare_output": "upper",
                    "compare_value": 0,
                },
                {
                    "indicator": "RSI",
                    "indicator_params": {"period": 14},
                    "output": "value",
                    "condition": "is_above",
                    "compare_to": "fixed_value",
                    "compare_value": 50,
                    "compare_indicator": "",
                    "compare_indicator_params": {},
                    "compare_output": "value",
                },
            ],
            "exit_take_profit": [{"type": "atr_tp", "params": {"multiplier": 2.5, "atr_period": 14}}],
            "exit_stop_loss": [{"type": "atr_sl", "params": {"multiplier": 1.5, "atr_period": 14}}],
            "exit_trailing": {"type": "trailing_atr", "value": 1.5, "atr_period": 14},
            "exit_break_even": {"trigger": 25, "lock": 5},
            "exit_time": None,
            "filters": [],
            "risk": {"preset": "moderate", "risk_per_trade": 2.0, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 4, "max_open_trades": 2, "max_drawdown": 20, "min_rr": 1.5},
        },
    },
    {
        "id": "macd_cross",
        "name": "MACD Crossover",
        "name_fa": "کراس مکدی",
        "icon": "🚀",
        "category": "momentum",
        "difficulty": "beginner",
        "description": "MACD crosses above signal line with ADX > 25 trend filter",
        "description_fa": "کراس مکدی بالای خط سیگنال با فیلتر روند ADX بالای ۲۵",
        "strategy": {
            "name": "MACD Crossover",
            "symbol": "EURUSD",
            "timeframe": "H1",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "MACD",
                    "indicator_params": {"fast": 12, "slow": 26, "signal": 9},
                    "output": "macd",
                    "condition": "crosses_above",
                    "compare_to": "indicator",
                    "compare_indicator": "MACD",
                    "compare_indicator_params": {"fast": 12, "slow": 26, "signal": 9},
                    "compare_output": "signal",
                    "compare_value": 0,
                },
                {
                    "indicator": "ADX",
                    "indicator_params": {"period": 14},
                    "output": "adx",
                    "condition": "is_above",
                    "compare_to": "fixed_value",
                    "compare_value": 25,
                    "compare_indicator": "",
                    "compare_indicator_params": {},
                    "compare_output": "value",
                },
            ],
            "exit_take_profit": [{"type": "atr_tp", "params": {"multiplier": 2.0, "atr_period": 14}}],
            "exit_stop_loss": [{"type": "atr_sl", "params": {"multiplier": 1.5, "atr_period": 14}}],
            "exit_trailing": {"type": "trailing_fixed", "value": 25, "atr_period": 14},
            "exit_break_even": None,
            "exit_time": None,
            "filters": [{"type": "spread_filter", "params": {"max_spread": 3}}],
            "risk": {"preset": "moderate", "risk_per_trade": 2.0, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 5, "max_open_trades": 3, "max_drawdown": 20, "min_rr": 1.5},
        },
    },
    {
        "id": "ichimoku_cloud",
        "name": "Ichimoku Cloud Break",
        "name_fa": "شکست ابر ایچیموکو",
        "icon": "☁️",
        "category": "ichimoku",
        "difficulty": "advanced",
        "description": "Price above cloud + Tenkan above Kijun + Chikou confirmation",
        "description_fa": "قیمت بالای ابر + تنکان بالای کیجون",
        "strategy": {
            "name": "Ichimoku Cloud Break",
            "symbol": "XAUUSD",
            "timeframe": "H4",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "PRICE",
                    "indicator_params": {"source": "close"},
                    "output": "value",
                    "condition": "is_above",
                    "compare_to": "indicator",
                    "compare_indicator": "ICHIMOKU",
                    "compare_indicator_params": {"tenkan": 9, "kijun": 26, "senkou_b": 52},
                    "compare_output": "senkou_a",
                    "compare_value": 0,
                },
                {
                    "indicator": "ICHIMOKU",
                    "indicator_params": {"tenkan": 9, "kijun": 26, "senkou_b": 52},
                    "output": "tenkan",
                    "condition": "is_above",
                    "compare_to": "indicator",
                    "compare_indicator": "ICHIMOKU",
                    "compare_indicator_params": {"tenkan": 9, "kijun": 26, "senkou_b": 52},
                    "compare_output": "kijun",
                    "compare_value": 0,
                },
            ],
            "exit_take_profit": [{"type": "atr_tp", "params": {"multiplier": 3.0, "atr_period": 14}}],
            "exit_stop_loss": [{"type": "atr_sl", "params": {"multiplier": 2.0, "atr_period": 14}}],
            "exit_trailing": {"type": "trailing_atr", "value": 2.5, "atr_period": 14},
            "exit_break_even": {"trigger": 40, "lock": 10},
            "exit_time": None,
            "filters": [],
            "risk": {"preset": "conservative", "risk_per_trade": 1.5, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 2, "max_open_trades": 2, "max_drawdown": 15, "min_rr": 2.0},
        },
    },
    {
        "id": "supertrend_ride",
        "name": "SuperTrend Rider",
        "name_fa": "سوار سوپرترند",
        "icon": "💪",
        "category": "trend",
        "difficulty": "beginner",
        "description": "Follow SuperTrend direction with EMA 50 confirmation",
        "description_fa": "دنبال کردن جهت سوپرترند با تایید EMA ۵۰",
        "strategy": {
            "name": "SuperTrend Rider",
            "symbol": "XAUUSD",
            "timeframe": "H1",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "PRICE",
                    "indicator_params": {"source": "close"},
                    "output": "value",
                    "condition": "crosses_above",
                    "compare_to": "indicator",
                    "compare_indicator": "SUPERTREND",
                    "compare_indicator_params": {"period": 10, "multiplier": 3.0},
                    "compare_output": "value",
                    "compare_value": 0,
                },
                {
                    "indicator": "PRICE",
                    "indicator_params": {"source": "close"},
                    "output": "value",
                    "condition": "is_above",
                    "compare_to": "indicator",
                    "compare_indicator": "EMA",
                    "compare_indicator_params": {"period": 50, "source": "close"},
                    "compare_output": "value",
                    "compare_value": 0,
                },
            ],
            "exit_take_profit": [{"type": "atr_tp", "params": {"multiplier": 2.5, "atr_period": 14}}],
            "exit_stop_loss": [{"type": "atr_sl", "params": {"multiplier": 1.5, "atr_period": 14}}],
            "exit_trailing": {"type": "trailing_atr", "value": 2.0, "atr_period": 14},
            "exit_break_even": {"trigger": 20, "lock": 5},
            "exit_time": None,
            "filters": [{"type": "session_filter", "params": {"sessions": ["london", "newyork"]}}],
            "risk": {"preset": "moderate", "risk_per_trade": 2.0, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 4, "max_open_trades": 2, "max_drawdown": 20, "min_rr": 1.5},
        },
    },
    {
        "id": "stoch_divergence",
        "name": "Stochastic Reversal",
        "name_fa": "برگشت استوکاستیک",
        "icon": "🔄",
        "category": "oscillator",
        "difficulty": "intermediate",
        "description": "Stochastic K crosses D in oversold/overbought zones",
        "description_fa": "کراس K و D استوکاستیک در مناطق اشباع",
        "strategy": {
            "name": "Stochastic Reversal",
            "symbol": "GBPUSD",
            "timeframe": "M30",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "STOCH",
                    "indicator_params": {"k_period": 14, "d_period": 3, "slowing": 3},
                    "output": "k",
                    "condition": "crosses_above",
                    "compare_to": "indicator",
                    "compare_indicator": "STOCH",
                    "compare_indicator_params": {"k_period": 14, "d_period": 3, "slowing": 3},
                    "compare_output": "d",
                    "compare_value": 0,
                },
                {
                    "indicator": "STOCH",
                    "indicator_params": {"k_period": 14, "d_period": 3, "slowing": 3},
                    "output": "k",
                    "condition": "is_below",
                    "compare_to": "fixed_value",
                    "compare_value": 30,
                    "compare_indicator": "",
                    "compare_indicator_params": {},
                    "compare_output": "value",
                },
            ],
            "exit_take_profit": [{"type": "fixed_tp", "params": {"pips": 40}}],
            "exit_stop_loss": [{"type": "fixed_sl", "params": {"pips": 25}}],
            "exit_trailing": {"type": "trailing_fixed", "value": 15, "atr_period": 14},
            "exit_break_even": {"trigger": 15, "lock": 3},
            "exit_time": {"bars": 15},
            "filters": [{"type": "spread_filter", "params": {"max_spread": 2.5}}],
            "risk": {"preset": "moderate", "risk_per_trade": 1.5, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 6, "max_open_trades": 3, "max_drawdown": 15, "min_rr": 1.5},
        },
    },
    {
        "id": "ema_ribbon",
        "name": "EMA Ribbon Trend",
        "name_fa": "نوار EMA روندی",
        "icon": "🌈",
        "category": "trend",
        "difficulty": "intermediate",
        "description": "EMA 8 > EMA 21 > EMA 55 alignment with MACD confirmation",
        "description_fa": "هم‌راستایی EMA 8 بالای 21 بالای 55 با تایید مکدی",
        "strategy": {
            "name": "EMA Ribbon Trend",
            "symbol": "XAUUSD",
            "timeframe": "H1",
            "direction": "both",
            "entry_logic": "AND",
            "entry_conditions": [
                {
                    "indicator": "EMA",
                    "indicator_params": {"period": 8, "source": "close"},
                    "output": "value",
                    "condition": "is_above",
                    "compare_to": "indicator",
                    "compare_indicator": "EMA",
                    "compare_indicator_params": {"period": 21, "source": "close"},
                    "compare_output": "value",
                    "compare_value": 0,
                },
                {
                    "indicator": "EMA",
                    "indicator_params": {"period": 21, "source": "close"},
                    "output": "value",
                    "condition": "is_above",
                    "compare_to": "indicator",
                    "compare_indicator": "EMA",
                    "compare_indicator_params": {"period": 55, "source": "close"},
                    "compare_output": "value",
                    "compare_value": 0,
                },
                {
                    "indicator": "MACD",
                    "indicator_params": {"fast": 12, "slow": 26, "signal": 9},
                    "output": "histogram",
                    "condition": "is_above",
                    "compare_to": "fixed_value",
                    "compare_value": 0,
                    "compare_indicator": "",
                    "compare_indicator_params": {},
                    "compare_output": "value",
                },
            ],
            "exit_take_profit": [{"type": "atr_tp", "params": {"multiplier": 3.0, "atr_period": 14}}],
            "exit_stop_loss": [{"type": "atr_sl", "params": {"multiplier": 1.5, "atr_period": 14}}],
            "exit_trailing": {"type": "trailing_atr", "value": 2.0, "atr_period": 14},
            "exit_break_even": {"trigger": 25, "lock": 5},
            "exit_time": None,
            "filters": [{"type": "trend_filter", "params": {"indicator": "ADX", "period": 14, "rule": "adx_above_25"}}],
            "risk": {"preset": "moderate", "risk_per_trade": 2.0, "lot_type": "risk_percent", "fixed_lot": 0.01, "max_daily_trades": 3, "max_open_trades": 2, "max_drawdown": 20, "min_rr": 2.0},
        },
    },
]

TEMPLATE_CATEGORIES = [
    {"id": "trend", "name_fa": "روندی", "icon": "📈"},
    {"id": "oscillator", "name_fa": "اسیلاتور", "icon": "📊"},
    {"id": "momentum", "name_fa": "مومنتوم", "icon": "🚀"},
    {"id": "volatility", "name_fa": "نوسان", "icon": "📉"},
    {"id": "ichimoku", "name_fa": "ایچیموکو", "icon": "☁️"},
]

DIFFICULTY_MAP = {
    "beginner": {"name_fa": "مبتدی", "color": "#22c55e"},
    "intermediate": {"name_fa": "متوسط", "color": "#f59e0b"},
    "advanced": {"name_fa": "حرفه‌ای", "color": "#ef4444"},
}


def get_templates():
    return {
        "templates": TEMPLATES,
        "categories": TEMPLATE_CATEGORIES,
        "difficulties": DIFFICULTY_MAP,
    }


def get_template(template_id):
    for t in TEMPLATES:
        if t["id"] == template_id:
            return t
    return None
